-- Migration: Fix Agent Attendance Timezone Bugs
-- Goal: Ensure the attendance record auto-generated by active status uses India Standard Time (IST) 
--       instead of UTC `CURRENT_DATE`. This prevents duplicates around midnight to 5:30 AM.

-- 1. Revise the attendance trigger to use IST for the DATE boundary
CREATE OR REPLACE FUNCTION mark_attendance_present()
RETURNS TRIGGER AS $$
BEGIN
    -- Only mark attendance if the agent is active
    IF NEW.is_active = TRUE THEN
        -- Safely upsert into attendance using IST date to match mobile app's local dates
        INSERT INTO attendance (agent_id, date, status, check_in_time)
        VALUES (
            NEW.agent_id,
            (NOW() AT TIME ZONE 'Asia/Kolkata')::DATE,
            'PRESENT',
            NOW()
        )
        ON CONFLICT (agent_id, date)
        DO UPDATE SET
            status = 'PRESENT', 
            updated_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Optional Cleanup: Remove completely anomalous rows from today if timestamps are wildly incorrect
-- (Only necessary if you have invalid records generated in the gap window)
-- DELETE FROM attendance WHERE date = (NOW() AT TIME ZONE 'Asia/Kolkata')::DATE AND check_in_time IS NULL;
